name: Render

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**.md'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Bogdanp/setup-racket@v1.8.1
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'  

      - name: Render image
        run: racket main.rkt > image.ppm

      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: ./*.ppm
